[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mymath"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
keywords = []
authors = [
  { name = "haghir", email = "47360153+haghir@users.noreply.github.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = []

[project.urls]
Documentation = "https://github.com/U.N. Owen/mymath#readme"
Issues = "https://github.com/U.N. Owen/mymath/issues"
Source = "https://github.com/U.N. Owen/mymath"

[tool.hatch.version]
path = "src/mymath/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/mymath tests}"

[tool.coverage.run]
source_pkgs = ["mymath", "tests"]
branch = true
parallel = true
omit = [
  "src/mymath/__about__.py",
]

[tool.coverage.paths]
mymath = ["src/mymath", "*/mymath/src/mymath"]
tests = ["tests", "*/mymath/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
