#!/usr/bin/env python3
import sys
import math

if len(sys.argv) != 3:
    print(f"Usage: {sys.argv[0]} <n> <k>")
    sys.exit(1)

n = int(sys.argv[1])
k = int(sys.argv[2])

prob = math.exp((-k * (k - 1)) / (2 * n))
print(f"No Duplicates: {prob}")
print(f"Duplicates   : {1 - prob}")
