#!/bin/bash

if [[ ! -n "${TMUX}" ]]; then
	echo "You are NOT in a tmux session." 1>&2
	exit 1
fi

no_claude=false
while getopts ":n" opt; do
	case ${opt} in
		n) no_claude=true ;;
		*) echo "Usage: devmux [-n] [path]" 1>&2; exit 1 ;;
	esac
done
shift $((OPTIND - 1))

if [[ $# -gt 0 ]]; then
	if [[ ! -d "${1}" ]]; then
		echo "\"${1}\" is not a directory" 1>&2
		exit 1
	fi
	cd "${1}"
fi

tmux new-window
tmux split-window -v -b
tmux resize-pane -y 70%
tmux split-window -h
tmux resize-pane -x 70%
tmux select-pane -D
tmux split-window -h
if [[ "${no_claude}" == false ]]; then
	tmux send-keys -t 0 "claude" Enter
fi
tmux send-keys -t 1 "emacs -nw" Enter
