#!/bin/bash

ROOTDIRS="${COLLECTIONS_ROOT}"
ADDDIR=""
VERBOSE=no
CURRENT_DIR="."

while getopts a:c:d:v OPT; do
	case ${OPT} in
		a) ADDDIR="${OPTARG}";;
		c) CURRENT_DIR="${OPTARG}";;
		d) ROOTDIRS="${OPTARG}";;
		v) VERBOSE=yes;;
		*) exit 1;;
	esac
done

if [[ "${ROOTDIRS}" = "" ]]; then
	echo "No root directories (-d) were specified." 1>&2
	exit 2
fi

ROOTDIR="$(collect-primary-root -d "${ROOTDIRS}")"
if [[ $? -ne 0 ]]; then
	exit 3
fi

TS=$(date +%Y%m%d%H%M%S)
YEAR=${TS:0:4}
MONTH=${TS:4:2}
DAY=${TS:6:2}
TIME=${TS:8:6}

LDIR="${YEAR}/${YEAR}-${MONTH}/${YEAR}-${MONTH}-${DAY}"
LNAME="${YEAR}${MONTH}${DAY}-${TIME}"
PREFIX="${LDIR}/${LNAME}"

idx=1
find -H "${CURRENT_DIR}" -mindepth 1 -maxdepth 1 -type f -not -name ".DS_Store" | sort | while read -r FPATH ; do
	if [[ "${VERBOSE}" = "yes" ]]; then
		echo "Adding ${FPATH}"
	fi

	FNAME="$(basename "${FPATH}")"
	EXT="${FNAME##*.}"
	if [[ "${EXT}" = "${FNAME}" ]]; then
		EXT=""
	else
		EXT=".${EXT}"
	fi

	while [ -e "${ROOTDIR}/${PREFIX}-${idx}"* ]; do
		idx=$((idx+1))
	done

	HASH="$(collect-file -s -h -d "${ROOTDIRS}" -f "${FPATH}" -l "${PREFIX}-${idx}${EXT}")"
	if [[ $? -ne 0 ]]; then
		continue
	fi

	collect-thumbnail -d "${ROOTDIRS}" -f ".objects/$(collect-objpath "${HASH}")"

	if [[ "${ADDDIR}" != "" ]]; then
		collect-file -d "${ROOTDIRS}" -f "${FPATH}" -l "${ADDDIR}/${LNAME}-${idx}${EXT}"
	fi

	idx=$((idx+1))
done
