#!/bin/bash

ROOTDIRS="${COLLECTIONS_ROOT}"
FPATH=""

while getopts d:f: OPT; do
	case ${OPT} in
		d) ROOTDIRS="${OPTARG}";;
		f) FPATH="${OPTARG}";;
		*) exit 1;;
	esac
done

if [[ "${ROOTDIRS}" = "" ]]; then
	echo "No root directories (-d) were specified." 1>&2
	exit 2
fi

if [[ "${FPATH}" = "" ]]; then
	echo "No file path (-f) was specified." 1>&2
	exit 3
fi

ROOTDIR="$(collect-primary-root -d "${ROOTDIRS}")"
if [[ $? -ne 0 ]]; then
	exit 4
fi

MIMETYPE="$(jq -r '.["mime"]["type"]' "${ROOTDIR}/${FPATH}.info")"
if [[ $? -ne 0 ]]; then
	echo "Failed to parse the information JSON." 1>&2
	exit 5
fi

function mklink()
{
	THUMBHASH="${1}"
	echo -n "${THUMBHASH}" > "${ROOTDIR}/${FPATH}.thumbnail"
	collect-clone -d "${ROOTDIRS}" -f "${FPATH}.thumbnail"
}

if [[ "${MIMETYPE}" = "image/"* ]]; then
	THUMBHASH="$(collect-image-thumbnail -d "${ROOTDIRS}" -f "${FPATH}")"
	if [[ $? -eq 0 ]]; then
		mklink "${THUMBHASH}"
	fi
elif [[ "${MIMETYPE}" = "video/"* ]]; then
	THUMBHASH="$(collect-video-thumbnail -d "${ROOTDIRS}" -f "${FPATH}")"
	if [[ $? -eq 0 ]]; then
		mklink "${THUMBHASH}"
	fi
fi
