#!/bin/bash

FPATH="${1}"

if [[ "${FPATH}" = "" ]]; then
	echo "No input path (-f) was specified." 1>&2
	exit 1
fi

if [ ! -f "${FPATH}" ]; then
	echo "${FPATH} is not a file." 1>&2
	exit 2
fi

IDENTIFY_COMMAND="magick identify"
if ! which magick > /dev/null 2>&1 ; then
	IDENTIFY_COMMAND="identify"
fi

MIMETYPE="$(file -L -b --mime-type "${FPATH}")"
ENCODING="$(file -L -b --mime-encoding "${FPATH}")"

JSON="\"mime\": $(jq --arg t "${MIMETYPE}" --arg e "${ENCODING}" -n \
   '{ "type": $t, "encoding": $e }')"

if [[ "${MIMETYPE}" = "image/"* ]]; then
	IMGSIZE="$(${IDENTIFY_COMMAND} -format "%w %h " "${FPATH}")"

	if [[ $? -eq 0 ]]; then
		WIDTH=$(echo "${IMGSIZE}" | awk '{ print $1 }')
		HEIGHT=$(echo "${IMGSIZE}" | awk '{ print $2 }')
		JSON="${JSON}, \"image\": $(jq -n \
			--arg w "${WIDTH}" --arg h "${HEIGHT}" \
			'{ "width": $w|tonumber, "height": $h|tonumber }')"
	fi
fi

if [[ "${MIMETYPE}" = "video/"* ]]; then
	VIDEOINFO="$(ffprobe -v error -print_format json -select_streams v:0 \
		-show_entries stream=width,height \
		-show_entries format=format_name,format_long_name "${FPATH}")"

	if [[ $? -eq 0 ]]; then
		WIDTH=$(echo "${VIDEOINFO}" | jq -r '.["streams"][0]["width"]')
		HEIGHT=$(echo "${VIDEOINFO}" | jq -r '.["streams"][0]["height"]')
		FORMAT=$(echo "${VIDEOINFO}" | jq -r '.["format"]["format_name"]')
		FORMATL=$(echo "${VIDEOINFO}" | jq -r '.["format"]["format_long_name"]')
		JSON="${JSON}, \"video\": $(jq -n \
			--arg w "${WIDTH}" --arg h "${HEIGHT}" \
			--arg f "${FORMAT}" --arg fl "${FORMATL}" \
			'{ "width": $w|tonumber, "height": $h|tonumber, "format_name": $f, "format_long_name": $fl }')"
	fi
fi

jq --argjson json "{ ${JSON} }" -n '$json'
