#!/bin/bash

ROOTDIRS="${COLLECTIONS_ROOT}"
REFRESH=no
VERBOSE=no

while getopts d:rv OPT; do
	case ${OPT} in
		d) ROOTDIRS="${OPTARG}";;
		r) REFRESH=yes;;
		v) VERBOSE=yes;;
		*) exit 1;;
	esac
done

if [[ "x${ROOTDIRS}" = "x" ]]; then
	echo "No root directories (-d) were specified." 1>&2
	exit 1
fi

ROOTDIR="${ROOTDIRS%%:*}"

find "${ROOTDIR}/.objects" -type f -name "*.info" | while read -r IPATH ; do
	FPATH="${IPATH%.info}"

	if [ "${REFRESH}" = "yes" ] || [ ! -e "${FPATH}.thumbnail" ]; then
		if [[ "${VERBOSE}" = "yes" ]]; then
			echo "Generating ${FPATH}.thumbnail"
		fi

		RELPATH=".objects/${FPATH##*/.objects/}"

		collect-thumbnail -d "${ROOTDIRS}" -f "${RELPATH}"
	fi
done
