#!/bin/bash

ROOTDIR="${COLLECTIONS_ROOT}"
REFRESH=no
VERBOSE=no

while getopts d:rv OPT; do
	case ${OPT} in
		d) ROOTDIR="${OPTARG}";;
		r) REFRESH=yes;;
		v) VERBOSE=yes;;
		*) exit 1;;
	esac
done

if [[ "x${ROOTDIR}" = "x" ]]; then
	echo "No root directory (-d) was specified." 1>&2
	exit 1
fi

find "${ROOTDIR}/.objects" -type f -not -name "*.*" | while read -r FPATH ; do
	if [ "${REFRESH}" = "yes" ] || [ ! -e "${FPATH}.info" ]; then
		if [[ "${VERBOSE}" = "yes" ]]; then
			echo "Generating ${FPATH}.info"
		fi

		collect-info "${FPATH}" > "${FPATH}.info"
	fi
done
