#!/bin/bash

ROOTDIRS="${COLLECTIONS_ROOT}"
FPATH=""
STRICT=no
SHOWHASH=no

while getopts d:f:hs OPT; do
	case ${OPT} in
		d) ROOTDIRS="${OPTARG}";;
		f) FPATH="${OPTARG}";;
		h) SHOWHASH=yes;;
		s) STRICT=yes;;
		*) exit 1;;
	esac
done

if [[ "${ROOTDIRS}" = "" ]]; then
	echo "No root directories (-d) were specified." 1>&2
	exit 2
fi

if [[ "${FPATH}" = "" ]]; then
	echo "No file path (-f) was specified." 1>&2
	exit 3
fi

if [ ! -f "${FPATH}" ]; then
	echo "${FPATH} is not a file." 1>&2
	exit 4
fi

ROOTDIR="$(collect-primary-root -d "${ROOTDIRS}")"
if [[ $? -ne 0 ]]; then
	exit 6
fi

HASH="$(sha256sum -b "${FPATH}" | awk '{ print $1 }' | tr '[:upper:]' '[:lower:]')"
OBJPATH="$(collect-objpath "${HASH}")"
OBJDIR="$(dirname "${OBJPATH}")"
OBJROOT="${ROOTDIR}/.objects"

DUPLICATED=no
if [ -e "${OBJROOT}/${OBJPATH}" ]; then
	DUPLICATED=yes
fi

if [ "${STRICT}" = "yes" ] && [ "${DUPLICATED}" = "yes" ]; then
	if [[ "${SHOWHASH}" = "yes" ]]; then
		echo "${HASH}"
	fi
	echo "${FPATH} already exists." 1>&2
	exit 7
fi

if [[ "${DUPLICATED}" = "no" ]]; then
	if ! mkdir -p "${OBJROOT}/${OBJDIR}"; then
		echo "Failed to create directories to store the file." 1>&2
		exit 8
	fi

	if ! cp -L "${FPATH}" "${OBJROOT}/${OBJPATH}"; then
		echo "Failed to copy." 1>&2
		exit 9
	fi

	chmod 444 "${OBJROOT}/${OBJPATH}"

	collect-info "${OBJROOT}/${OBJPATH}" > "${OBJROOT}/${OBJPATH}.info"

	collect-clone -d "${ROOTDIRS}" -f ".objects/${OBJPATH}"
	collect-clone -d "${ROOTDIRS}" -f ".objects/${OBJPATH}.info"
fi

if [[ "${SHOWHASH}" = "yes" ]]; then
	echo "${HASH}"
fi
