#!/bin/bash

ROOTDIR="${COLLECTIONS_ROOT}"
FPATH=""
LPATH=""
STRICT=no

while getopts d:f:l:s OPT; do
	case ${OPT} in
		d) ROOTDIR="${OPTARG}";;
		f) FPATH="${OPTARG}";;
		l) LPATH="${OPTARG}";;
		s) STRICT=yes;;
		*) exit 1;;
	esac
done

if [[ "x${ROOTDIR}" = "x" ]]; then
	echo "A root directory (-d) was not specified." 1>&2
	exit 2
fi

if [ ! -f "${FPATH}" ]; then
	echo "${FPATH} is not a file." 1>&2
	exit 3
fi

if [[ "${LPATH:0:1}" = "/" ]]; then
	echo "A link path (-l) must be a relative path." 1>&2
	exit 4
fi

OBJROOT="${ROOTDIR}/.objects"

echo "Adding ${FPATH}"

HASH="$(sha256sum -b "${FPATH}")"
HASH1="${HASH:0:2}"
HASH2="${HASH:2:4}"
HASH3="${HASH:6:26}"
HASH4="${HASH:32:32}"

OBJDIR="${HASH1}/${HASH2}/${HASH3}"
OBJPATH="${OBJDIR}/${HASH4}"

FNAME="$(basename "${FPATH}")"
EXT="${FNAME##*.}"
if [[ "${EXT}" = "${FNAME}" ]]; then
	EXT=""
else
	EXT=".${EXT}"
fi

DUPLICATED=no
if [ -e "${OBJROOT}/${OBJPATH}"* ]; then
	DUPLICATED=yes
fi

if [ "${STRICT}" = "yes" ] && [ "${DUPLICATED}" = "yes" ]; then
	echo "${FPATH} already exists." 1>&2
	exit 5
fi

if [[ "${DUPLICATED}" = "no" ]]; then
	mkdir -p "${OBJROOT}/${OBJDIR}"
	cp "${FPATH}" "${OBJROOT}/${OBJPATH}${EXT}"
fi

if [[ "x${LPATH}" != "x" ]]; then
	LDIR="$(dirname "${LPATH}")"
	mkdir -p "${ROOTDIR}/${LDIR}"

	RELPATH=".objects/${OBJPATH}${EXT}"
	while [[ "${LDIR}" != "." ]]; do
		RELPATH="../${RELPATH}"
		LDIR="$(dirname "${LDIR}")"
	done

	ln -s "${RELPATH}" "${ROOTDIR}/${LPATH}"
fi
