#!/bin/bash

ROOTDIRS="${COLLECTIONS_ROOT}"
FPATH=""

while getopts d:f: OPT; do
	case ${OPT} in
		d) ROOTDIRS="${OPTARG}";;
		f) FPATH="${OPTARG}";;
		*) exit 1;;
	esac
done

if [[ "x${ROOTDIRS}" = "x" ]]; then
	echo "No root directories (-d) were specified." 1>&2
	exit 2
fi

if [[ "x${FPATH}" = "x" ]]; then
	echo "No file path (-f) was specified." 1>&2
	exit 3
fi

MIMETYPE="$(jq -r '.["mime"]["type"]' "${FPATH}.info")"
if [[ $? -ne 0 ]]; then
	echo "Failed to parse the information JSON." 1>&2
	exit 4
fi

if [[ "${MIMETYPE}" = "image/"* ]]; then
	THUMBHASH="$(collect-image-thumbnail -d "${ROOTDIRS}" -f "${FPATH}")"
	if [[ $? -eq 0 ]]; then
		echo -n "${THUMBHASH}" > "${FPATH}.thumbnail"
		collect-clone -d "${ROOTDIRS}" -f "${FPATH}.thumbnail"
	fi
elif [[ "${MIMETYPE}" = "video/"* ]]; then
	THUMBHASH="$(collect-video-thumbnail -d "${ROOTDIRS}" -f "${FPATH}")"
	if [[ $? -eq 0 ]]; then
		echo -n "${THUMBHASH}" > "${FPATH}.thumbnail"
		collect-clone -d "${ROOTDIRS}" -f "${FPATH}.thumbnail"
	fi
fi
