#!/bin/bash

ROOTDIRS="${COLLECTIONS_ROOT}"
DEPTH=1
VERBOSE=""
WKDIR="$(pwd)"

while getopts d:h:v OPT; do
	case ${OPT} in
		d) ROOTDIRS="${OPTARG}";;
		h) ((DEPTH=${OPTARG}));;
		v) VERBOSE="-v";;
		*) exit 1;;
	esac
done

if [[ "${ROOTDIRS}" = "" ]]; then
	echo "No root directories (-d) were specified." 1>&2
	exit 1
fi

find -L "${WKDIR}" -mindepth 1 -maxdepth ${DEPTH} -type d | while read -r DPATH ; do
	DPATH="${DPATH#${WKDIR}/}"
	collect ${VERBOSE} -c "${DPATH}" -d "${ROOTDIRS}" -a "fav/${DPATH}"
done

collect ${VERBOSE} -c "${WKDIR}" -d "${ROOTDIRS}"
