#!/bin/bash

ROOTDIRS="${COLLECTIONS_ROOT}"
FPATH=""

while getopts d:f: OPT; do
	case ${OPT} in
		d) ROOTDIRS="${OPTARG}";;
		f) FPATH="${OPTARG}";;
		*) exit 1;;
	esac
done

if [[ "x${ROOTDIRS}" = "x" ]]; then
	echo "No root directories (-d) were specified." 1>&2
	exit 1
fi

if [[ "x${FPATH}" = "x" ]]; then
	echo "No input path (-f) was specified." 1>&2
	exit 2
fi

ROOTDIR="${ROOTDIRS%%:*}"

if [ ! -f "${ROOTDIR}/${FPATH}" ]; then
	echo "${ROOTDIR}/${FPATH} is not a file." 1>&2
	exit 3
fi

IDENTIFY_COMMAND="magick identify"
CONVERT_COMMAND="magick"
if ! which magick > /dev/null 2>&1 ; then
	IDENTIFY_COMMAND="identify"
	CONVERT_COMMAND="convert"
fi

IMGSIZE="$(${IDENTIFY_COMMAND} -format "%w %h " "${ROOTDIR}/${FPATH}")"
if [[ $? -ne 0 ]]; then
	echo "Failed to get the image size." 1>&2
	exit 4
fi

WIDTH="$(echo "${IMGSIZE}" | awk '{ print $1 }')"
HEIGHT="$(echo "${IMGSIZE}" | awk '{ print $2 }')"

if [ ${WIDTH} -le 100 ] && [ ${HEIGHT} -le 100 ]; then
	collect-file -h -d "${ROOTDIRS}" -f "${ROOTDIR}/${FPATH}"
	exit 0
fi

TMPDIR="$(mktemp -d)"
THUMBPATH="${TMPDIR}/thumbnail)"

TIMES=""
if [[ ${WIDTH} -lt ${HEIGHT} ]]; then
	TIMES="x"
fi

if ! ${CONVERT_COMMAND} "${ROOTDIR}/${FPATH}" -resize "${TIMES}100" -strip "${THUMBPATH}"; then
	echo "Failed to create a thumbnail." 1>&2
	rm -rf "${TMPDIR}"
	exit 5
fi

collect-file -h -d "${ROOTDIRS}" -f "${THUMBPATH}"
rm -rf "${TMPDIR}"
