#!/bin/bash

ROOTDIR="${COLLECTIONS_ROOT}"
REFRESH=no

while getopts d:r OPT; do
	case ${OPT} in
		d) ROOTDIR="${OPTARG}";;
		r) REFRESH=yes;;
		*) exit 1;;
	esac
done

if [[ "x${ROOTDIR}" = "x" ]]; then
	echo "No root directory (-d) was specified." 1>&2
	exit 1
fi

find "${ROOTDIR}/.objects" -type f \( -not -name "*.info" -and -not -name ".DS_Store" \) | while read -r FPATH ; do
	if [ "${REFRESH}" = "yes" ] || [ ! -e "${FPATH}.info" ]; then
		collect-info "${FPATH}" > "${FPATH}.info"
	fi
done
