#!/bin/bash

ROOTDIR="${COLLECTIONS_ROOT}"
VERBOSE=no
WKDIR="$(pwd)"

while getopts d:v OPT; do
	case ${OPT} in
		d) ROOTDIR="${OPTARG}";;
		v) VERBOSE=yes;;
		*) exit 1;;
	esac
done

if [[ "x${ROOTDIR}" = "x" ]]; then
	echo "No root directory (-d) was specified." 1>&2
	exit 1
fi

find "${WKDIR}" -mindepth 1 -maxdepth 1 -type d | while read -r DPATH ; do
	collect -c "${DPATH}" -d "${ROOTDIR}" -a "fav/$(basename "${DPATH}")"
done

collect -c "${WKDIR}" -d "${ROOTDIR}"
