#!/bin/bash

ROOTDIRS="${COLLECTIONS_ROOT}"
VERBOSE=""
WKDIR="$(pwd)"

while getopts d:v OPT; do
	case ${OPT} in
		d) ROOTDIRS="${OPTARG}";;
		v) VERBOSE="-v";;
		*) exit 1;;
	esac
done

if [[ "${ROOTDIRS}" = "" ]]; then
	echo "No root directories (-d) were specified." 1>&2
	exit 1
fi

find -L "${WKDIR}" -mindepth 1 -maxdepth 1 -type d | while read -r DPATH ; do
	collect ${VERBOSE} -c "${DPATH}" -d "${ROOTDIRS}" -a "fav/$(basename "${DPATH}")"
done

collect ${VERBOSE} -c "${WKDIR}" -d "${ROOTDIRS}"
