#!/bin/bash

ROOTDIR="${COLLECTIONS_ROOT}"
FPATH=""
LPATH=""
STRICT=no
SHOWHASH=no

while getopts d:f:hl:s OPT; do
	case ${OPT} in
		d) ROOTDIR="${OPTARG}";;
		f) FPATH="${OPTARG}";;
		h) SHOWHASH=yes;;
		l) LPATH="${OPTARG}";;
		s) STRICT=yes;;
		*) exit 1;;
	esac
done

if [[ "x${ROOTDIR}" = "x" ]]; then
	echo "No root directory (-d) was specified." 1>&2
	exit 2
fi

if [[ "x${FPATH}" = "x" ]]; then
	echo "No file path (-f) was specified." 1>&2
	exit 3
fi

if [ ! -f "${FPATH}" ]; then
	echo "${FPATH} is not a file." 1>&2
	exit 4
fi

if [[ "${LPATH:0:1}" = "/" ]]; then
	echo "A link path (-l) must be a relative path." 1>&2
	exit 5
fi

HASH="$(sha256sum -b "${FPATH}" | awk '{ print $1 }' | tr '[:upper:]' '[:lower:]')"
OBJPATH="$(collect-objpath "${HASH}")"
OBJDIR="$(dirname "${OBJPATH}")"
OBJROOT="${ROOTDIR}/.objects"

DUPLICATED=no
if [ -e "${OBJROOT}/${OBJPATH}" ]; then
	DUPLICATED=yes
fi

if [ "${STRICT}" = "yes" ] && [ "${DUPLICATED}" = "yes" ]; then
	echo "${FPATH} already exists." 1>&2
	exit 6
fi

if [[ "${DUPLICATED}" = "no" ]]; then
	if ! mkdir -p "${OBJROOT}/${OBJDIR}"; then
		echo "Failed to create a directory to store the file." 1>&2
		exit 7
	fi

	if ! cp -L "${FPATH}" "${OBJROOT}/${OBJPATH}"; then
		echo "Failed to copy." 1>&2
		exit 8
	fi

	chmod 444 "${OBJROOT}/${OBJPATH}"

	collect-info "${OBJROOT}/${OBJPATH}" > "${OBJROOT}/${OBJPATH}.info"
fi

if [[ "x${LPATH}" != "x" ]]; then
	LDIR="$(dirname "${LPATH}")"
	mkdir -p "${ROOTDIR}/${LDIR}"

	RELPATH=".objects/${OBJPATH}"
	while [[ "${LDIR}" != "." ]]; do
		RELPATH="../${RELPATH}"
		LDIR="$(dirname "${LDIR}")"
	done

	ln -s "${RELPATH}" "${ROOTDIR}/${LPATH}"
fi

if [[ "${SHOWHASH}" = "yes" ]]; then
	echo "${HASH}"
fi
