#!/bin/bash

ROOTDIRS="${COLLECTIONS_ROOT}"
FPATH=""

while getopts d:f: OPT; do
	case ${OPT} in
		d) ROOTDIRS="${OPTARG}";;
		f) FPATH="${OPTARG}";;
		*) exit 1;;
	esac
done

if [[ "${ROOTDIRS}" = "" ]]; then
	echo "No root directories (-d) were specified." 1>&2
	exit 2
fi

ROOTDIR="$(collect-primary-root -d "${ROOTDIRS}")"
if [[ $? -ne 0 ]]; then
	exit 3
fi
ROOTDIRS="${ROOTDIRS#*:}"

if [[ "${FPATH}" = "" ]]; then
	echo "No file path (-f) was specified." 1>&2
	exit 4
fi

if [[ "${FPATH}" = "/"* ]]; then
	echo "The file path (-f) must be a relative one." 1>&2
	exit 5
fi

if [[ "${FPATH}" = "~/"* ]]; then
	echo "The file path (-f) must be a relative one." 1>&2
	exit 5
fi

if [[ "${ROOTDIR}" = "${ROOTDIRS}" ]]; then
	# ROOTDIRS has just one directory.
	exit 0
fi

if [ ! -f "${ROOTDIR}/${FPATH}" ]; then
	echo "${ROOTDIR}/${FPATH} is not a file." 1>&2
	exit 6
fi

collect-root-dirs -d "${ROOTDIRS}" | while read -r BKROOTDIR; do
	BKPATH="${BKROOTDIR}/${FPATH}"

	BKDIR="$(dirname "${BKPATH}")"
	mkdir -p "${BKDIR}"

	cp -f -p -P "${ROOTDIR}/${FPATH}" "${BKPATH}"

	RELDIR="$(dirname "${FPATH}")"
	while [[ "${RELDIR}" != "." ]]; do
		chmod --reference="${ROOTDIR}/${RELDIR}" "${BKROOTDIR}/${RELDIR}"
		touch -r "${ROOTDIR}/${RELDIR}" "${BKROOTDIR}/${RELDIR}"
		RELDIR="$(dirname "${RELDIR}")"
	done
done
