#!/bin/bash

ROOTDIRS="${COLLECTIONS_ROOT}"
REFRESH=no
VERBOSE=no

while getopts d:rv OPT; do
	case ${OPT} in
		d) ROOTDIRS="${OPTARG}";;
		r) REFRESH=yes;;
		v) VERBOSE=yes;;
		*) exit 1;;
	esac
done

if [[ "${ROOTDIRS}" = "" ]]; then
	echo "No root directories (-d) were specified." 1>&2
	exit 2
fi

ROOTDIR="$(collect-primary-root -d "${ROOTDIRS}")"
if [[ $? -ne 0 ]]; then
	exit 3
fi

find -H "${ROOTDIR}/.objects" -type f -not -name "*.*" | while read -r FPATH ; do
	if [ "${REFRESH}" = "yes" ] || [ ! -e "${FPATH}.info" ]; then
		if [[ "${VERBOSE}" = "yes" ]]; then
			echo "Generating ${FPATH}.info"
		fi

		RELPATH=".objects/${FPATH##*/.objects/}"

		collect-info "${FPATH}" > "${FPATH}.info"
		collect-clone -d "${ROOTDIRS}" -f "${RELPATH}.info"
	fi
done
