#!/bin/bash

ROOTDIRS="${COLLECTIONS_ROOT}"
REFRESH=no
VERBOSE=no

while getopts d:rv OPT; do
	case ${OPT} in
		d) ROOTDIRS="${OPTARG}";;
		r) REFRESH=yes;;
		v) VERBOSE=yes;;
		*) exit 1;;
	esac
done

if [[ "x${ROOTDIRS}" = "x" ]]; then
	echo "No root directories (-d) were specified." 1>&2
	exit 1
fi

ROOTDIR="${ROOTDIRS%%:*}"

find "${ROOTDIR}/.objects" -type f -not -name "*.*" | while read -r FPATH ; do
	if [ "${REFRESH}" = "yes" ] || [ ! -e "${FPATH}.info" ]; then
		if [[ "${VERBOSE}" = "yes" ]]; then
			echo "Generating ${FPATH}.info"
		fi

		RELPATH=".objects/${FPATH##*/.objects/}"

		collect-info "${FPATH}" > "${FPATH}.info"
		collect-clone -d "${ROOTDIRS}" -f "${RELPATH}.info"
	fi
done
