#!/bin/bash

ROOTDIR="${COLLECTIONS_ROOT}"
ADDDIR=""
VERBOSE=no
CURRENT_DIR="."

while getopts a:c:d:v OPT; do
	case ${OPT} in
		a) ADDDIR="${OPTARG}";;
		c) CURRENT_DIR="${OPTARG}";;
		d) ROOTDIR="${OPTARG}";;
		v) VERBOSE=yes;;
		*) exit 1;;
	esac
done

if [[ "x${ROOTDIR}" = "x" ]]; then
	echo "No root directory (-d) was specified." 1>&2
	exit 1
fi

TS=$(date +%Y%m%d%H%M%S)
YEAR=${TS:0:4}
MONTH=${TS:4:2}
DAY=${TS:6:2}
TIME=${TS:8:6}

LDIR="${YEAR}/${YEAR}-${MONTH}/${YEAR}-${MONTH}-${DAY}"
LNAME="${YEAR}${MONTH}${DAY}-${TIME}"
PREFIX="${LDIR}/${LNAME}"

idx=1
find "${CURRENT_DIR}" -mindepth 1 -maxdepth 1 -type f -not -name ".DS_Store" | sort | while read -r FPATH ; do
	if [[ "${VERBOSE}" = "yes" ]]; then
		echo "Adding ${FPATH}"
	fi

	FNAME="$(basename "${FPATH}")"
	EXT="${FNAME##*.}"
	if [[ "${EXT}" = "${FNAME}" ]]; then
		EXT=""
	else
		EXT=".${EXT}"
	fi

	while [ -e "${ROOTDIR}/${PREFIX}-${idx}"* ]; do
		idx=$((idx+1))
	done

	HASH="$(collect-file -s -h -d "${ROOTDIR}" -f "${FNAME}" -l "${PREFIX}-${idx}${EXT}")"
	if [[ $? -ne 0 ]]; then
		continue
	fi

	OBJPATH="${ROOTDIR}/.objects/$(collect-objpath "${HASH}")"
	collect-thumbnail -d "${ROOTDIR}" -f "${OBJPATH}"

	if [[ "x${ADDDIR}" != "x" ]]; then
		collect-file -d "${ROOTDIR}" -f "${FNAME}" -l "${ADDDIR}/${LNAME}-${idx}${EXT}"
	fi

	idx=$((idx+1))
done
