#!/bin/bash

{
	if [[ $# -gt 0 ]]; then
		echo "${1}"
	else
		cat -
	fi
} |\
sed -e 's/A/𝑨/g' |\
sed -e 's/B/𝑩/g' |\
sed -e 's/C/𝑪/g' |\
sed -e 's/D/𝑫/g' |\
sed -e 's/E/𝑬/g' |\
sed -e 's/F/𝑭/g' |\
sed -e 's/G/𝑮/g' |\
sed -e 's/H/𝑯/g' |\
sed -e 's/I/𝑰/g' |\
sed -e 's/J/𝑱/g' |\
sed -e 's/K/𝑲/g' |\
sed -e 's/L/𝑳/g' |\
sed -e 's/M/𝑴/g' |\
sed -e 's/N/𝑵/g' |\
sed -e 's/O/𝑶/g' |\
sed -e 's/P/𝑷/g' |\
sed -e 's/Q/𝑸/g' |\
sed -e 's/R/𝑹/g' |\
sed -e 's/S/𝑺/g' |\
sed -e 's/T/𝑻/g' |\
sed -e 's/U/𝑼/g' |\
sed -e 's/V/𝑽/g' |\
sed -e 's/W/𝑾/g' |\
sed -e 's/X/𝑿/g' |\
sed -e 's/Y/𝒀/g' |\
sed -e 's/Z/𝒁/g' |\
sed -e 's/a/𝒂/g' |\
sed -e 's/b/𝒃/g' |\
sed -e 's/c/𝒄/g' |\
sed -e 's/d/𝒅/g' |\
sed -e 's/e/𝒆/g' |\
sed -e 's/f/𝒇/g' |\
sed -e 's/g/𝒈/g' |\
sed -e 's/h/𝒉/g' |\
sed -e 's/i/𝒊/g' |\
sed -e 's/j/𝒋/g' |\
sed -e 's/k/𝒌/g' |\
sed -e 's/l/𝒍/g' |\
sed -e 's/m/𝒎/g' |\
sed -e 's/n/𝒏/g' |\
sed -e 's/o/𝒐/g' |\
sed -e 's/p/𝒑/g' |\
sed -e 's/q/𝒒/g' |\
sed -e 's/r/𝒓/g' |\
sed -e 's/s/𝒔/g' |\
sed -e 's/t/𝒕/g' |\
sed -e 's/u/𝒖/g' |\
sed -e 's/v/𝒗/g' |\
sed -e 's/w/𝒘/g' |\
sed -e 's/x/𝒙/g' |\
sed -e 's/y/𝒚/g' |\
sed -e 's/z/𝒛/g'
